name: Run Package Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DATABASE_URL: postgresql://username:password@localhost:0000/database-name
  BETTER_AUTH_SECRET: aFakeSecret1234567890=

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10 # Specify your major pnpm version

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm" # Enables automatic caching for faster runs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run check
        run: pnpm run check
